### PR TITLE
fix: Jetty 9.4 - Use JDK 17 for Zulu OpenJDK 17 Alpine image

### PR DESCRIPTION
**Pull request by jnehlmeier**

### CODE REVIEW

**Review by joakime — APPROVED** [review]

**Comment by lachlan-roberts** [comment]
@jnehlmeier looks like you might have to resign the eclipse ECA

see:
https://api.eclipse.org/git/eca/status/gh/jetty/jetty.docker/173

**Comment by jnehlmeier** [comment]
@lachlan-roberts Oh, didn't know Jetty requires an ECA. I think I don't want to create an Eclipse Account and sign ECA just for fixing a typo for an old Jetty version in this PR and executing a shell script in PR #174. Feel free to close both PRs or use my work in those PRs as you like.

**Comment by joakime** [comment]
> @lachlan-roberts Oh, didn't know Jetty requires an ECA. I think I don't want to create an Eclipse Account and sign ECA just for fixing a typo for an old Jetty version in this PR and executing a shell script in PR #174. Feel free to close both PRs or use my work in those PRs as you like.

FYI, any submitted PR to any Eclipse Foundation project has this ECA requirement.
It is not unique to Jetty.

**Comment by lachlan-roberts** [comment]
closed with commit 61109cf646d015a23faee8938d96be2867748279

**Pull request closed without merging**
