### PR TITLE
add amazoncoretto images based on amazon linux 2023

### PR DESCRIPTION
**Pull request by lachlan-roberts**
Add images for Amazon Linux 2023, which is supposed to replace AL2.

Support for AL2 is ending on 30 Jun 2025.

### CODE REVIEW

**Comment by lachlan-roberts** [comment]
Yep just saw it needed `gnupg2-full`.

But I have done it in a different way such that it will work on both AL2 and AL2023, because these files are updated with a script pulling from the `baseDockerfile-amazoncorretto` Dockerfile.

**Comment by alzaicko** [comment]
al2023 uses dnf as its default package manager. I think it's better to abandon yum and use only dnf

**Comment by joakime** [comment]
Documentation about AL2023 changes to package management.

https://docs.aws.amazon.com/linux/al2023/ug/package-management.html

**Comment by lachlan-roberts** [comment]
The `yum` command is just a pointer to the `dnf` command. So I think its fine to leave yum and reduce the duplication of maintaining separate docker files for AL2 and AL2023. Until after 30 Jun 2025 where we can drop support for AL2 and and only use`dnf`.

**Comment by alzaicko** [comment]
Thank you, I'm waiting for the new version to appear on dockerhub

**Comment by lachlan-roberts** [comment]
@alzaicko This PR has been merged https://github.com/docker-library/official-images/pull/18016.

So the new versions should be available very soon.

**Pull request merged**
